dojo.provide("drawboard.Constant");
drawboard.Constant = {
	MouseAction:{
		NONE:0,
		MOUSEDOWN:1,
		MOUSEMOVE:2,
		MOUSEUP:3,
		MOUSEOVER:4,
		MOUSECLICK:5,
		MOUSEOUT:6
	},
	ActionStatus:{
		NONE:0,
		SELECTING:1,
		DRAWING:2,
		MOVING:3,
		MARKING:4,
		RESIZING:5,
		ROTATING:6,
		POLEMOVING:7,
		MOTION:8,
		TEXT:9
	},
	Decorate:{
		SKELETON:0,
		MARK:1,
		ROTATOR:2,
		MOTIONANCHOR:3,
		CHARACTER:4,
		Graph:5,
		CENTER:6,
		OUTLET:7
	},
	Direction:{
		EAST:0,
		EASTNORTH:1,
		NORTH:2,
		WESTNORTH:3,
		WEST:4,
		WESTSOUTH:5,
		SOUTH:6,
		EASTSOUTH:7,
		END:8
	},
	Path:{
		NONE:"",
		MOVE:"M",
		RMOVE:"m",		//R present relative
		LINE:"L",
		RLINE:"l",
		HORIZON:"H",	//present horizontal line without y coordinate
		RHORIZON:"h",
		VERTICAL:"V",	//present vertical line without x coordinate
		RVERTICAL:"v",
		CUBIC:"C",		
		RCUBIC:"c",
		CUBICSMOOTH:"S",
		CUBICRSMOOTH:"s",
		QUADRATIC:"Q",
		RQUADRATIC:"q",
		QUADRATICSMOOTH:"T",
		RQUADRATICSMOOTH:"t",
		ARC:"A",
		RARC:"a",
		CLOSE:"Z",
		RCLOSE:"z"
	},
	Command:{
		CREATEVSDELETECOMMAND:"createvsdelete",
		RESIZECOMMAND:"resize",
		MOVECOMMAND:"move",
		ROTATECOMMAND:"rotate",
		ZOOMCOMMAND:"zoom",
		STYLECOMMAND:"style",
		ADDVSDELTECONSTRAINCOMMAND:"addvsdeleteconstrain",
		COMBINEVSDEVIDEDCOMMAND:"combinevsdevided",
		COMPOSITECOMMAND:"composite",
		MOTIONCOMMAND:"motion"
	},
	Symbol:{
		concat:"&&"
	},
	Toolbar:{
		COLORPALETTE:0,
		DROPDOWNLIST:1,
		DIALOGUE:2
	}
};